### ISSUE TITLE
Using String Algorithms.

### ISSUE THREAD

**Issue by code-monk08** [Crypt0knights/Plagiarism-Detector#25]
since our project uses string algorithms, there is no clear idea as how we are supposed to use them, so here is my take on this.

- [ ] If the uploaded document is in PDF format, we first need to capture the text from PDF, if the doc is in TXT format than all good.

- [ ] now that captured text needs to be tokenized to sentence using NLP algorithms.

- [ ] after this is done, our API gives us three keys as result, for the uploaded document those keys are URL , Match Ratio %, No. of copied words as JSON and It doesn't give the actual words or sentences which are copied

- [ ] so here string matching algorithms will come into play, we can make a result section in our website where it will be divided into three sub vertical sections, something like this:

![image](https://user-images.githubusercontent.com/19390263/57189248-b30fa500-6f29-11e9-8d7d-b9591c0ada5d.png)

If there are any suggestions, discuss here.

**Comment by nightwarrior-xxx** [comment]
@code-monk08 Idea is good. Here are my reviews :-
1. No need for upload button
2. After submitting the files and pressing the a button for results we will display redirect the user of another page which you are saying. 
3. Also we will use some visualization tool. chatJS etc.

**Comment by code-monk08** [comment]
chart.js to visualize what?

**Comment by code-monk08** [comment]
>     2. After submitting the files on home page and pressing the a button for results we will redirect the user to another page which you are saying.
> alright, this is fine.

**Comment by code-monk08** [comment]
>     3\. Also we will use some visualization tool. chatJS etc.
chart.js to visualize what?

**Comment by nightwarrior-xxx** [comment]
> chart.js to visualize what?
To visualize no. of copied words and % matched

**Comment by sidntrivedi012** [comment]
We can visualize it on the same page since we don't have much data to be visualized. Also we will have to look into the child process functionality of node in order to get the NLP python script running.
