### ISSUE TITLE
Scraping text from PDFs.

### ISSUE THREAD

**Issue by sidntrivedi012** [Crypt0knights/Plagiarism-Detector#45]
We'll have to device a way to scrape out the text from the pdfs. Maybe using any pip module in order to get it done in the `scrape.py` file itself?

**Comment by nightwarrior-xxx** [comment]
I am working on it

**Comment by nightwarrior-xxx** [comment]
Script is done now adding it to scrape.py

**Comment by sidntrivedi012** [comment]
I am not working on it.

**Comment by nightwarrior-xxx** [comment]
Done

**Comment by sidntrivedi012** [comment]
Awesome. Closing this issue then.
